
def create_prompt(data, task_type):
    if task_type == 'storytelling':
        prompt = f"Create a narrative for the following dataset: {data.to_string()}"
    elif task_type == 'analysis':
        prompt = f"Analyze the following dataset: {data.to_string()}"
    elif task_type == 'comparison':
        prompt = f"Compare and contrast key features in this dataset: {data.to_string()}"
    else:
        prompt = f"Provide insights for this dataset: {data.to_string()}"

    return prompt
                

def create_viz_prompt(visualization_goal, target_audience, visual_style):
    visualization_goals = {
        "Analyze data": "The purpose of this visualization is to analyze the dataset in detail, focusing on uncovering and exploring deep relationships between different variables. The visual should provide insights into how these data points correlate or interact, helping the user identify key patterns or anomalies. It should be designed for individuals who want to dig deeper into the data, providing enough granularity to allow for a comprehensive understanding of the underlying structure. This visualization should support data exploration, enabling the viewer to draw informed conclusions or hypotheses.",
        "Answer questions": "The purpose of this visualization is to directly address specific questions posed by the data. The visual should focus on providing clear and concise answers, drawing from relevant data points to illuminate insights. The visualization needs to be structured in a way that emphasizes the key answers and minimizes distractions, helping users quickly interpret the information. It should prioritize accuracy and clarity, allowing users to find the answer they seek with minimal effort and maximum understanding.",
        "Communicate ideas": "This visualization is intended to communicate key insights or concepts effectively to the viewer. The focus should be on clarity and simplicity, ensuring that the main ideas stand out and are easily understood by the target audience. The design should emphasize key points, using visual cues such as color, shapes, or annotations to highlight important information. The goal is to share insights in a visually compelling way that resonates with the audience, helping them grasp the message quickly and clearly.",
        "Find/Reveal patterns": "The goal of this visualization is to help reveal trends, patterns, or correlations within the dataset. The visual should be crafted in a way that uncovers these hidden insights, making it easier for users to detect emerging relationships. It should be designed for those seeking to discover meaningful connections, emphasizing the visualization’s ability to highlight unexpected patterns. By focusing on pattern discovery, the visual should guide users toward new insights and prompt further investigation into the data.",
        "Make decisions": "This visualization is intended to support decision-making by presenting data in a way that informs strategic choices. The visual should prioritize actionable insights, focusing on key metrics or relationships that directly impact the decision at hand. It should be designed to distill complex information into a clear and concise format, enabling decision-makers to weigh options, evaluate risks, or explore outcomes. The visualization must balance detail and clarity, allowing for both big-picture analysis and in-depth examination as needed.",
        "Tell a story": "The goal of this visualization is to narrate a data-driven story, guiding the viewer through a series of insights in a coherent and engaging manner. It should focus on crafting a narrative that connects data points in a meaningful way, ensuring that the flow of information feels natural and compelling. Visual elements such as timelines, annotations, and progressive reveals can be used to build the story. The design should capture the viewer’s attention and draw them through the data, helping them connect with the overall message."
    }
    target_audience = {
        "Experts": "This visualization is designed for a specialized audience with advanced knowledge in the field. The focus should be on delivering detailed, precise, and comprehensive insights that allow for in-depth analysis. The content can assume familiarity with technical terms, complex data structures, and nuanced relationships between variables. The visual should not oversimplify the information but rather offer layers of depth and complexity, providing experts with the tools to derive significant insights, conduct thorough evaluations, and form data-driven conclusions based on their specialized understanding.",
        "Stakeholders": "This visualization is intended for decision-makers, providing clear and actionable insights that can guide their strategic choices. The visual should be straightforward, highlighting key data points and trends that are most relevant for the decisions at hand. It should prioritize clarity over complexity, ensuring that stakeholders can quickly understand the information presented. Visualizations should focus on the big picture, helping decision-makers grasp the implications of the data and identify opportunities or risks.",
        "General Audience": "This visualization is designed for a broad audience, so it should prioritize simplicity and accessibility. The visual should be easy to understand, even for viewers without specialized knowledge of the data or topic. Clear labels, straightforward charts, and an uncluttered layout are key to ensuring that the message is communicated effectively. The design should focus on making the data approachable, with an emphasis on helping users quickly grasp the key insights or stories being told.",
       
    }
    visual_style = {
         "Professional": "The visual style should be clean, formal, and business-oriented, suitable for reports or presentations in a corporate setting. Colors should be neutral and muted, emphasizing professionalism and clarity. The layout should be organized and minimal, prioritizing legibility and precision. The overall design should convey a sense of authority and reliability, using visual elements that reflect a polished, structured approach to the data. This style is ideal for conveying serious insights in a clear and credible manner.",
        "Playful": "The visualization should adopt a bright, engaging, and fun visual style that is both visually stimulating and approachable, particularly for younger audiences or educational purposes. Colors should be vibrant, and the design should include lively elements that evoke curiosity and excitement. The layout should be simple yet dynamic, focusing on making data more accessible and less intimidating. This style is meant to captivate the viewer’s attention, making learning or data exploration enjoyable while ensuring clarity and understanding without overwhelming the audience with too much detail.",
        "Modern minimalism": "The visual style should be sleek, contemporary, and minimal, focusing on simplicity and clarity. There should be an emphasis on whitespace, clean lines, and a restrained color palette. The design should be elegant and efficient, removing unnecessary elements and distractions to focus on the key data points. This style is ideal for audiences who appreciate modern design aesthetics and value clarity, helping them engage with the data without visual clutter.",
        "Warm and Inviting": "The visualization should have a friendly, welcoming feel, using soft, warm colors and gentle design elements that create a sense of approachability. The style should evoke comfort and connection, making the data more accessible to a wide range of audiences. Visual elements should feel natural and unpretentious, helping to guide users through the information in a way that feels personal and engaging. This style is particularly effective for making data feel less intimidating and more relatable.",
        "Tech-savvy": "The visual style should feel futuristic and digital, using elements that convey a cutting-edge, technological aesthetic. This can include vibrant colors, geometric shapes, and modern typography. The design should evoke a sense of innovation, emphasizing the role of technology in shaping data insights. This style works best for topics related to technology, science, or innovation, where the goal is to convey a sense of progress and sophistication through the visual representation of data.",
        "Artistic Flair": "The visualization should be creative and visually rich, incorporating artistic elements that elevate the aesthetic appeal of the data. Bold colors, unique patterns, and expressive layouts can be used to make the visualization feel more like a work of art than a traditional data chart. The style should engage the viewer’s senses, creating an emotional connection while still communicating the underlying data effectively. This approach works well when the goal is to make the data presentation feel unique and memorable."
    }
    return "The current selections are as follows: Visualization Goal: " + visualization_goal + ": " + visualization_goals[visualization_goal] + " Target Audience: " + target_audience + ": " + target_audience[target_audience] + " Visual Style: " + visual_style + ": " + visual_style[visual_style]    



                